### ISSUE TITLE
v0.9.2 => uncaughtException: /node_modules/xml2json/node_modules/joi/lib/index.js:5 const Hoek = require('hoek'); ^^^^^ Use of const in strict mode.

### ISSUE THREAD

**Issue by micahd** [buglabs/node-xml2json#125]
v0.9.2 just broke our prod build - the error is:  

uncaughtException: /node_modules/xml2json/node_modules/joi/lib/index.js:5 const Hoek = require('hoek'); ^^^^^ Use of const in strict mode.

I had to revert our package.json to v0.9.0 to have it build again.

**Comment by c4milo** [comment]
Yes, that's my bad, my apologies. Also, @micahd, use https://docs.npmjs.com/cli/shrinkwrap to avoid 3rd-party deps breaking your builds. 

After upgrading this package dependencies I realized some of them started using ES6 features because they are considered stable since Node 4.x. So, I unpublished 0.9.2 and published  0.10.0 as it breaks like in your case.

**Comment by micahd** [comment]
Ok very good, thanks.

**Comment by c4milo** [comment]
I'm sorry again for the mishap.

**Comment by micahd** [comment]
I just tested with with 0.10.0 for the pacakge.json version on a staging build and it still has the same issue:  "Use of const in strict mode."  This exception is generated at the path /node_modules/xml2json/lib/xml2json.js

**Comment by c4milo** [comment]
Right, the reason for increasing the minor and not the patch number was
because it breaks on Node versions older than 4.x. In those cases the
version to use is 0.9.1 or lower.
