### ISSUE TITLE
Is there a way to get a built binary version?

### ISSUE THREAD

**Issue by SeanHayes** [buglabs/node-xml2json#133]
I'd like to use this on my node site, but I deploy via Docker, and it seems that node-gyp requires Python and GCC to be present inside the Docker image.

**Comment by c4milo** [comment]
If you deploy using Docker you can bake the module inside your Docker image.

**Comment by SeanHayes** [comment]
Is there a way to do that without baking in all the build dependencies too?

**Comment by c4milo** [comment]
http://lmgtfy.com/?q=nodejs+app+as+single+binary

**Comment by c4milo** [comment]
Hey @SeanHayes, I'm sorry for the rude response :/ . The alternatives I found are: 

1. https://github.com/jxcore/jxcore-release/
2. https://github.com/nexe/nexe
3. http://enclosejs.com/

1 seems unmaintained, 3 seems to be closed source and commercial. 2 does not support native modules and wouldn't work with node-xml2json due to node-expat which is a native module :/

I would suggest exploring  node-xml2json alternatives, perhaps https://www.npmjs.com/package/xmljs. 

I hope this helps you and apologies again for the rude answer above.
